### ISSUE TITLE
Error :  any character yet crash program

### ISSUE THREAD

**Issue by Sullivaniut** [DorianLudm/Python_RPG#21]
# BugFix

When i select play with a character, and i have not create one
The program propose to back and crash

image :
![ErrorPythonRPG](https://github.com/DorianLudm/Python_RPG/assets/90240238/2d88d182-1b70-4ea0-a90d-eff706501922)

Good luck :)

**Comment by DorianLudm** [comment]
Hello Sullivan!

Thank you for your report, the game should now work properly with the new version available on the main branch!
Happy Testing!
